### ISSUE TITLE
Use mobile app instead of Vita?

### ISSUE THREAD

**Issue by beaumartinez** [dsokoloski/ps4-wake#3]
Hi @dsokoloski,

I don't have a Vita, but I do have the mobile app (which I use regularly to wake my PS4). Do you know if there's a way to use that instead? I could inspect the traffic with `mitmproxy` or something.

Cheers.

**Comment by dsokoloski** [comment]
Hey Beau!

It's probably possible to snoop the traffic from the mobile app to get the key you need for ps4-wake (I haven't tried myself).  However, an easier way may be to use ps4-waker.  Another developer has taken ps4-wake and expanded upon it greatly... you can actually start an application, and put the PS4 in to rest mode remotely using ps4-waker.  It's written in Node.js I think... here's the URL:

https://www.npmjs.com/package/ps4-waker

I would try this first... seems to be more feature-complete than my version.

**Comment by beaumartinez** [comment]
Thanks @dsokoloski. I just installed that and set it up—very painless process!
